version: "3.4"

services:
  bearbot-discord:
    image: bearbot-discord
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: bearbot.debug.env
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
